version: '3'

services:
  front:
    build: ./front
    ports:
      - "3000:3000"
    volumes:
      - ./front:/front
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
    networks:
      - app-network
  api:
    build: ./api
    ports:
      - "3001:3000"
    volumes:
      - .:/chatApp
    working_dir: /chatApp
    command: /bin/sh -c "rm -f tmp/pids/server.pid && cd api/src &&bundle exec rails s -p 3000 -b '0.0.0.0'"
    stdin_open: true
    tty: true
    networks:
      - app-network
    depends_on:
      - db
  db:
    build: ./db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: app_db
    volumes:
      - app-data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  app-data:
networks:
  app-network:
    driver: bridge