default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  encoding: utf8
  username: root
  password: root
  host: db

development:
  <<: *default
  database: app_db
  username: root
  password: root
  host: db
